t0bst4r/home-assistant-matter-hub

- package-lock.json
- packages/backend/src/matter/behaviors/basic-information-server.ts
> fix(basic-information): consider maxLength of device properties

- packages/backend/src/home-assistant/home-assistant-client.ts
> fix: ignore entities by their hidden and disabled state

- README.md
> chore: add link to 'buy me a coffee' to the documentation

- packages/backend/src/home-assistant/match-entity-filter.test.ts
- packages/backend/src/home-assistant/match-entity-filter.ts
- packages/backend/src/matter/behaviors/color-temperature-control-server.ts
- packages/backend/src/matter/behaviors/extended-color-control-server.ts
- packages/backend/src/matter/behaviors/level-control-server.ts
> fix: support pattern matching

- packages/backend/src/home-assistant/match-entity-filter.ts
- packages/backend/src/home-assistant/subscribe-entities.ts
- packages/backend/src/matter/behaviors/thermostat-server.ts
- packages/backend/src/matter/behaviors/thermostat/heating-and-cooling-thermostat-server.ts
- packages/backend/src/matter/devices/climate-device.ts
- packages/common/src/domains/climate.ts
> fix(climate): allow auto-mode only

- packages/backend/src/matter/behaviors/boolean-state-server.ts
- packages/backend/src/matter/behaviors/occupancy-sensing-server.ts
- packages/backend/src/matter/devices/binary-sensor-device.ts
> fix(binary_sensor): safe access the config from the state

- packages/backend/src/matter/behaviors/thermostat-server.ts
> feat(climate): add thermostatRunningMode only for autoMode

- packages/backend/src/matter/behaviors/thermostat-server.ts
- packages/frontend/src/components/cluster/ClusterState.tsx
> fix(climate): use entity state value as fallback for all status reports

- .github/workflows/issue_comments.yml
- apps/home-assistant-matter-hub/package.json
- build/index.js
- nx.json
- package-lock.json
- packages/backend/bundle.js
- packages/backend/package.json
- packages/backend/src/bootstrap.ts
- packages/backend/src/cli.ts
- packages/backend/src/commands/start.ts
- packages/backend/src/environment/environment.ts
- packages/backend/src/home-assistant/home-assistant-client.ts
- packages/backend/src/matter/behaviors/color-control-server.ts
- packages/backend/src/utils/apply-patch-state.test.ts
- packages/backend/src/utils/apply-patch-state.ts
- packages/backend/tsconfig.json
> fix(light): default hue and saturation to 0 when not available

- packages/backend/src/storage/create-storage-service.ts
- packages/backend/src/utils/apply-patch-state.ts
> fix(lights): remove old and wrong properties from lights

- .github/workflows/release.yml
> fix(ci): automatic releases for the addon repository including changelog

- packages/backend/src/matter/behaviors/boolean-state-server.ts
> fix(binary_sensor): made config of boolean state cluster optional

- packages/backend/src/matter/bridge/create-device.ts
- packages/backend/src/matter/devices/scene-device.ts
> fix(scene): default to off state to be able to turn it on

- packages/backend/src/matter/behaviors/level-control-server.ts
- packages/backend/src/matter/behaviors/on-off-server.ts
- packages/backend/src/matter/devices/light/light-level-control-config.ts
- packages/common/src/clusters/level-control.ts
- packages/frontend/src/components/cluster/states/LevelControlState.tsx
> fix(lights): preserve last level control state

- packages/frontend/src/components/fabric/FabricIcon.tsx
Fixes: https://github.com/t0bst4r/home-assistant-matter-hub/issues/253
> fix(frontend): Add second Samsung vendor ID

- packages/backend/src/matter/behaviors/fan-control-server.ts
> fix(fan-control): always set fan mode sequence

- packages/backend/src/matter/behaviors/auto-off-server.ts
- packages/backend/src/matter/bridge/create-device.test.ts
- packages/backend/src/matter/bridge/create-device.ts
- packages/backend/src/matter/devices/input-button-device.ts
- packages/common/src/home-assistant-domain.ts
> feat(input_button): add support for input_button entities

- packages/backend/src/matter/behaviors/basic-information-server.ts
- packages/backend/src/matter/behaviors/on-off-server.ts
> fix(on-off): allow sending on and off commands, when already on or off

- packages/backend/src/matter/behaviors/color-control-server.ts
> fix(colorControl): validate min and max mireds to stay in bounds

- README.md
- package-lock.json
- packages/backend/src/matter/behaviors/utils/window-covering-server-utils.test.ts
- packages/backend/src/matter/behaviors/utils/window-covering-server-utils.ts
- packages/backend/src/matter/behaviors/window-covering-server.ts
- packages/backend/src/matter/devices/cover-device.ts
- packages/backend/src/matter/devices/fan-device.ts
- packages/common/src/bridge-data.ts
- packages/common/src/schemas/bridge-config-schema.ts
fixes #384
fixes #297
fixes #291
> feat(cover): allow covers to mimic HA behaviors

- packages/backend/src/matter/behaviors/auto-off-server.ts
> fix(input_button): turn the matter device 'on' for a short time

- packages/backend/src/matter/behaviors/thermostat-server.ts
- packages/common/src/domains/climate.ts
Possible fix for this comment: https://github.com/t0bst4r/home-assistant-matter-hub/issues/449#issuecomment-2600986948
> fix(thermostat): Check if setting temperature range is supported

- packages/backend/src/matter/bridge/create-device.test.ts
- packages/backend/src/matter/bridge/create-device.ts
- packages/backend/src/matter/devices/button-device.ts
- packages/common/src/home-assistant-domain.ts
Attempt to let button entity working like an on/off device type. 
Using same auto-off behavior like for tirgger or scenes.
> handle button entity the same way as input_button

- apps/home-assistant-matter-hub/package.json
- package-lock.json
- packages/backend/package.json
- packages/backend/src/api/web-api.ts
- packages/frontend/src/components/bridge/BridgeDetails.tsx
- packages/frontend/src/components/notifications/notifications-provider.tsx
- packages/frontend/src/pages/bridge-details/BridgeDetailsPage.tsx
- packages/frontend/src/pages/bridge-details/BridgeMoreMenu.tsx
- packages/frontend/src/pages/bridges/BridgesPage.tsx
- packages/frontend/src/pages/edit-bridge/CreateBridgePage.tsx
- packages/frontend/src/pages/edit-bridge/EditBridgePage.tsx
- packages/frontend/src/routes.tsx
- packages/frontend/src/theme/AppFooter.tsx
- packages/frontend/src/theme/AppLogo.tsx
> fix: minor frontend fixes

- packages/backend/src/environment/storage/custom-storage.ts
- packages/backend/src/home-assistant/home-assistant-client.ts
- packages/backend/src/storage/bridge-storage.ts
- packages/frontend/src/main.tsx
> fix(storage): fixed storage migration of the last release

- packages/backend/src/matter/devices/climate/behaviors/climate-thermostat-server.ts
Related with https://github.com/t0bst4r/home-assistant-matter-hub/issues/692
> fix(climate): use 'current_temperature' attribute to get current temperature

- packages/backend/src/matter/behaviors/color-control-server.ts
> fix(light): ensure color temperature is always within boundaries
